### Consultar todos los estudiantes
GET http://127.0.0.1:8000/api/app/estudiante/

### Consultar un solo estudiante
GET http://127.0.0.1:8000/api/app/estudiante/1055

### Eliminar estudiante

DELETE http://127.0.0.1:8000/api/app/estudiante/12345

### Ingresar un nuevo estudiante
POST http://127.0.0.1:8000/api/app/estudiante/
Content-Type: 'application/json'

{
   "cod": "10556",
   "nombres": "yessid",
   "email": "yesjim@test.com"
}

### Actualizar estudiante
PUT http://127.0.0.1:8000/api/app/estudiante/1055
Content-Type: 'application/json'

{
   "nombres": "Julio",
   "email": "jul@test.com"
}

### Crear registro de notas
POST http://127.0.0.1:8000/api/app/nota/
Content-Type: 'application/json'

{
  "actividad": "trabajo 3",
  "nota": "3",
  "codEstudiante": "1055"
}

### imprimir todos los registros de notas
GET http://127.0.0.1:8000/api/app/nota/
